name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    container: golang:v1.15-alpine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: vsftpdmgrdb
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run go test
        run: go test ./...
        env:
          TEST_DATABASE_URL: postgres://postgres@postgres/vsftpdmgrdb?sslmode=disable
